"""empty message

Revision ID: 297845b2422
Revises: None
Create Date: 2015-05-02 13:54:25.420741

"""

# revision identifiers, used by Alembic.
revision = '297845b2422'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_class',
    sa.Column('report_type', sa.SmallInteger(), nullable=False),
    sa.Column('report_name', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('report_type')
    )
    op.create_table('word_all',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word_string', sa.String(length=8), nullable=False),
    sa.Column('reported', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('word_id'),
    sa.UniqueConstraint('word_string')
    )
    op.create_table('candidate_word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word_all.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('report_log',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.SmallInteger(), nullable=False),
    sa.Column('report_detail', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['report_type'], ['report_class.report_type'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word_all.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('word_search',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word_parsed', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word_all.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('rank_log',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('elapsed_date', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('rank_good', sa.Integer(), nullable=True),
    sa.Column('rank_bad', sa.Integer(), nullable=True),
    sa.Column('viewed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word_search.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id', 'elapsed_date')
    )
    op.create_table('word_rank',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('rank_good', sa.Integer(), nullable=True),
    sa.Column('rank_bad', sa.Integer(), nullable=True),
    sa.Column('viewed', sa.Integer(), nullable=True),
    sa.Column('fresh_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word_search.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_rank')
    op.drop_table('rank_log')
    op.drop_table('word_search')
    op.drop_table('report_log')
    op.drop_table('candidate_word')
    op.drop_table('word_all')
    op.drop_table('report_class')
    ### end Alembic commands ###
