"""empty message

Revision ID: 36d95c7ef03
Revises: 564737d246d
Create Date: 2015-04-26 10:37:14.268021

"""

# revision identifiers, used by Alembic.
revision = '36d95c7ef03'
down_revision = '564737d246d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
