"""empty message

Revision ID: 3e1e35a84f
Revises: None
Create Date: 2015-04-25 20:31:41.653734

"""

# revision identifiers, used by Alembic.
revision = '3e1e35a84f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_log',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('elapsed_date', sa.SmallInteger(), nullable=False),
    sa.Column('rank_good', sa.Integer(), nullable=True),
    sa.Column('rank_bad', sa.Integer(), nullable=True),
    sa.Column('viewed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word_search.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('word_rank',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('rank_good', sa.Integer(), nullable=True),
    sa.Column('rank_bad', sa.Integer(), nullable=True),
    sa.Column('viewed', sa.Integer(), nullable=True),
    sa.Column('fresh_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word_search.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_rank')
    op.drop_table('rank_log')
    ### end Alembic commands ###
