"""empty message

Revision ID: 564737d246d
Revises: 32026765795
Create Date: 2015-04-25 21:43:52.009220

"""

# revision identifiers, used by Alembic.
revision = '564737d246d'
down_revision = '32026765795'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
